//
//  QuotesManager.swift
//  QuotesApp
//
//  Created by Doni Silva on 24/08/24.
//

import Foundation

public class QuotesManager {
    
    public func getRandomQuote() -> QuoteEntity {
        let index = Int(arc4random_uniform(UInt32(quotes.count)))
        return quotes[index]
    }
    
    public let quotes: [QuoteEntity] = [
        QuoteEntity(quote: "SteveJobsQuote1".localized,
                    author: "Steve Jobs",
                    image: "steve_jobs"),
        QuoteEntity(quote: "SteveJobsQuote2".localized,
                    author: "Steve Jobs",
                    image: "steve_jobs"),
        QuoteEntity(quote: "SteveJobsQuote3".localized,
                    author: "Steve Jobs",
                    image: "steve_jobs"),
        QuoteEntity(quote: "SteveJobsQuote4".localized,
                    author: "Steve Jobs",
                    image: "steve_jobs"),
        
        QuoteEntity(quote: "JesusChristQuote1".localized,
                    author: "JesusChristAuthor".localized,
                    image: "jesus_de_nazare"),
        QuoteEntity(quote: "JesusChristQuote2".localized,
                    author: "JesusChristAuthor".localized,
                    image: "jesus_de_nazare"),
        QuoteEntity(quote: "JesusChristQuote3".localized,
                    author: "JesusChristAuthor".localized,
                    image: "jesus_de_nazare"),
        
        QuoteEntity(quote: "BruceLeeQuote1".localized,
                    author: "Bruce Lee",
                    image: "bruce_lee"),
        QuoteEntity(quote: "BruceLeeQuote2".localized,
                    author: "Bruce Lee",
                    image: "bruce_lee"),
        
        QuoteEntity(quote: "ArthurConanQuote1".localized,
                    author: "Arthur Conan Doyle",
                    image: "arthur_conan_doyle"),
        QuoteEntity(quote: "ArthurConanQuote2".localized,
                    author: "Arthur Conan Doyle",
                    image: "arthur_conan_doyle"),
        QuoteEntity(quote: "ArthurConanQuote3".localized,
                    author: "Arthur Conan Doyle",
                    image: "arthur_conan_doyle"),
        
        QuoteEntity(quote: "AristotleQuote1".localized,
                    author: "AristotleAuthor".localized,
                    image: "aristoteles"),
        QuoteEntity(quote: "AristotleQuote2".localized,
                    author: "AristotleAuthor".localized,
                    image: "aristoteles"),
        QuoteEntity(quote: "AristotleQuote3".localized,
                    author: "AristotleAuthor".localized,
                    image: "aristoteles"),
        
        QuoteEntity(quote: "JohnDonneQuote1".localized,
                    author: "John Donne",
                    image: "john_donne"),
        QuoteEntity(quote: "JohnDonneQuote2".localized,
                    author: "John Donne",
                    image: "john_donne"),
        QuoteEntity(quote: "JohnDonneQuote3".localized,
                    author: "John Donne",
                    image: "john_donne"),
        
        QuoteEntity(quote: "BlaisePascalQuote1".localized,
                    author: "Blaise Pascal",
                    image: "blaise_pascal"),
        QuoteEntity(quote: "BlaisePascalQuote2".localized,
                    author: "Blaise Pascal",
                    image: "blaise_pascal"),
        QuoteEntity(quote: "BlaisePascalQuote3".localized,
                    author: "Blaise Pascal",
                    image: "blaise_pascal"),
        
        QuoteEntity(quote: "RichardRestakQuote1".localized,
                    author: "Richard Restak",
                    image: "richard_restak"),
        
        QuoteEntity(quote: "CharlesChaplinQuote1".localized,
                    author: "Charles Chaplin",
                    image: "charles_chaplin"),
        QuoteEntity(quote: "CharlesChaplinQuote2".localized,
                    author: "Charles Chaplin",
                    image: "charles_chaplin"),
        QuoteEntity(quote: "CharlesChaplinQuote3".localized,
                    author: "Charles Chaplin",
                    image: "charles_chaplin"),
        QuoteEntity(quote: "CharlesChaplinQuote4".localized,
                    author: "Charles Chaplin",
                    image: "charles_chaplin"),
        
        QuoteEntity(quote: "MarkTwainQuote1".localized,
                    author: "Mark Twain",
                    image: "mark_twain"),
        QuoteEntity(quote: "MarkTwainQuote2".localized,
                    author: "Mark Twain",
                    image: "mark_twain"),
        QuoteEntity(quote: "MarkTwainQuote3".localized,
                    author: "Mark Twain",
                    image: "mark_twain"),
        
        QuoteEntity(quote: "ThomasCarlyleQuote1".localized,
                    author: "Thomas Carlyle",
                    image: "thomas_carlyle"),
        QuoteEntity(quote: "ThomasCarlyleQuote2".localized,
                    author: "Thomas Carlyle",
                    image: "thomas_carlyle"),
        QuoteEntity(quote: "ThomasCarlyleQuote3".localized,
                    author: "Thomas Carlyle",
                    image: "thomas_carlyle"),
        
        QuoteEntity(quote: "MahatmaGandhiQuote1".localized,
                    author: "Mahatma Gandhi",
                    image: "mahatma_gandhi"),
        QuoteEntity(quote: "MahatmaGandhiQuote2".localized,
                    author: "Mahatma Gandhi",
                    image: "mahatma_gandhi"),
        QuoteEntity(quote: "MahatmaGandhiQuote3".localized,
                    author: "Mahatma Gandhi",
                    image: "mahatma_gandhi"),
        QuoteEntity(quote: "MahatmaGandhiQuote4".localized,
                    author: "Mahatma Gandhi",
                    image: "mahatma_gandhi"),
        QuoteEntity(quote: "MahatmaGandhiQuote5".localized,
                    author: "Mahatma Gandhi",
                    image: "mahatma_gandhi"),
        QuoteEntity(quote: "MahatmaGandhiQuote6".localized,
                    author: "Mahatma Gandhi",
                    image: "mahatma_gandhi"),
        
        QuoteEntity(quote: "DavidAllenQuote1".localized,
                    author: "David Allen",
                    image: "david_allen"),
        QuoteEntity(quote: "DavidAllenQuote2".localized,
                    author: "David Allen",
                    image: "david_allen"),
        QuoteEntity(quote: "DavidAllenQuote3".localized,
                    author: "David Allen",
                    image: "david_allen"),
        
        QuoteEntity(quote: "WayneGretzyQuote1".localized,
                    author: "Wayne Gretzky",
                    image: "wayne_gretzky"),
        QuoteEntity(quote: "WayneGretzyQuote2".localized,
                    author: "Wayne Gretzky",
                    image: "wayne_gretzky"),
        
        QuoteEntity(quote: "AbrahamMaslowQuote1".localized,
                    author: "Abraham Maslow",
                    image: "abraham_maslow"),
        QuoteEntity(quote: "AbrahamMaslowQuote2".localized,
                    author: "Abraham Maslow",
                    image: "abraham_maslow"),
        QuoteEntity(quote: "AbrahamMaslowQuote3".localized,
                    author: "Abraham Maslow",
                    image: "abraham_maslow"),
        
        QuoteEntity(quote: "AlbertEinsteinQuote1".localized,
                    author: "Albert Einstein",
                    image: "albert_einstein"),
        QuoteEntity(quote: "AlbertEinsteinQuote2".localized,
                    author: "Albert Einstein",
                    image: "albert_einstein"),
        QuoteEntity(quote: "AlbertEinsteinQuote3".localized,
                    author: "Albert Einstein",
                    image: "albert_einstein"),
        QuoteEntity(quote: "AlbertEinsteinQuote4".localized,
                    author: "Albert Einstein",
                    image: "albert_einstein"),
        QuoteEntity(quote: "AlbertEinsteinQuote5".localized,
                    author: "Albert Einstein",
                    image: "albert_einstein"),
        
        QuoteEntity(quote: "VoltaireQuote1".localized,
                    author: "Voltaire",
                    image: "voltaire"),
        QuoteEntity(quote: "VoltaireQuote2".localized,
                    author: "Voltaire",
                    image: "voltaire"),
        QuoteEntity(quote: "VoltaireQuote3".localized,
                    author: "Voltaire",
                    image: "voltaire"),
        
        QuoteEntity(quote: "BobMarleyQuote1".localized,
                    author: "Bob Marley",
                    image: "bob_marley"),
        QuoteEntity(quote: "BobMarleyQuote2".localized,
                    author: "Bob Marley",
                    image: "bob_marley"),
        QuoteEntity(quote: "BobMarleyQuote3".localized,
                    author: "Bob Marley",
                    image: "bob_marley"),
        
        QuoteEntity(quote: "AmeliaEarhartQuote1".localized,
                    author: "Amelia Earhart",
                    image: "amelia_earhart"),
        QuoteEntity(quote: "AmeliaEarhartQuote2".localized,
                    author: "Amelia Earhart",
                    image: "amelia_earhart"),
        QuoteEntity(quote: "AmeliaEarhartQuote3".localized,
                    author: "Amelia Earhart",
                    image: "amelia_earhart"),
        
        QuoteEntity(quote: "JohnLennonQuote1".localized,
                    author: "John Lennon",
                    image: "john_lennon"),
        QuoteEntity(quote: "JohnLennonQuote2".localized,
                    author: "John Lennon",
                    image: "john_lennon"),
        QuoteEntity(quote: "JohnLennonQuote3".localized,
                    author: "John Lennon",
                    image: "john_lennon"),
        
        QuoteEntity(quote: "BuddhaQuote1".localized,
                    author: "Buddha",
                    image: "buddha"),
        QuoteEntity(quote: "BuddhaQuote2".localized,
                    author: "Buddha",
                    image: "buddha"),
        QuoteEntity(quote: "BuddhaQuote3".localized,
                    author: "Buddha",
                    image: "buddha"),
        
        QuoteEntity(quote: "HenryFordQuote1".localized,
                    author: "Henry Ford",
                    image: "henry_ford"),
        QuoteEntity(quote: "HenryFordQuote2".localized,
                    author: "Henry Ford",
                    image: "henry_ford"),
        QuoteEntity(quote: "HenryFordQuote3".localized,
                    author: "Henry Ford",
                    image: "henry_ford"),
        
        QuoteEntity(quote: "ZigZiglarQuote1".localized,
                    author: "Zig Ziglar",
                    image: "zig_ziglar"),
        QuoteEntity(quote: "ZigZiglarQuote2".localized,
                    author: "Zig Ziglar",
                    image: "zig_ziglar"),
        QuoteEntity(quote: "ZigZiglarQuote3".localized,
                    author: "Zig Ziglar",
                    image: "zig_ziglar"),
    ]
}
